#cloud-config
package_update: true
package_upgrade: true

packages:
  - snapd

runcmd:
  - |
    systemctl daemon-reload
    
    systemctl restart snapd.service
    
    snap wait system seed
    
    snap install microstack --beta --devmode
    microstack init --auto --control

    microstack.openstack keypair create --public-key /home/${ssh_user}/.ssh/authorized_keys ${microstack_keypair_name}
    microstack.openstack security group create lab-secgroup
    microstack.openstack security group rule create --proto icmp lab-secgroup
    microstack.openstack security group rule create --proto tcp --dst-port 22 lab-secgroup
